// =============================================================================
// data_reduction.cpp
// -----------------------------------------------------------------------------
// Phase 6 — Data Reduction Model
//
// PURPOSE:
//   Computes Kurzke-Riegler map scale factors by running the turbofan cycle
//   at multiple power settings and comparing cycle output against "measured"
//   data. With real engine data, replace the synthetic operating points with
//   actual test cell or flight test measurements.
//
// WHAT IT DOES:
//   1. Runs the turbofan cycle at N operating points (power settings)
//   2. Records station data as synthetic "measurements" at each point
//   3. Computes four scale factors per component at each operating point:
//        s_Wc = Wc_perf / Wc_map
//        s_Nc = Nc_perf / Nc_map
//        s_PR = (PR_perf - 1) / (PR_map - 1)
//        s_Ef = eff_perf / eff_map
//   4. Averages scale factors across all operating points (MDP Multi-
//      Design-Point method)
//   5. Writes updated SCALE_* fields to the map files
//   6. Prints a data reduction report
//
// NPSS ALIGNMENT:
//   Mirrors NPSS "flight test data correlation" mode.
//   Multi-Design-Point (MDP) method — same as Boeing BRE NPSS workflow.
//   Reference: "The Development of an NPSS Engine Cycle Model to Match
//   Engine Cycle Data, Using a Multi-Design-Point Method", AIAA 2021-0876.
//
// SYNTHETIC DATA NOTE:
//   Operating points are generated by running our own cycle model at
//   different shaft speeds. This validates the infrastructure.
//   Replace with real test cell data (CSV or similar) when available.
//   Format for real data substitution documented in measured_data section.
//
// SCALE FACTOR FORMULAS (Kurzke & Riegler, ASME 2000-GT-0006):
//   s_Wc = Wc_perf / Wc_map_at_operating_point
//   s_Nc = Nc_perf / Nc_map_at_operating_point
//   s_PR = (PR_perf - 1) / (PR_map_at_operating_point - 1)
//   s_Ef = eff_perf / eff_map_at_operating_point
//
// MAP FILE UPDATE:
//   Writes SCALE_PR, SCALE_EFF, SCALE_WC, SCALE_NC to map file headers.
//   Preserves all other map content unchanged.
//
// USAGE:
//   Run from build directory:
//     ./data_reduction
//   Map files in ../maps/synthetic/ are updated in place.
//   Run GasTurbineEngineModel after to verify updated maps.
//
// UNITS — SI throughout:
//   Wc   [kg/s corrected]
//   Nc   [RPM corrected]
//   PR   [-]
//   eff  [-]
// =============================================================================

#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <vector>
#include <string>
#include <cmath>
#include <numeric>

// Engine element headers
#include "Inlet.h"
#include "Fan.h"
#include "Splitter.h"
#include "Compressor.h"
#include "Combustor.h"
#include "Turbine.h"
#include "Nozzle.h"
#include "FanNozzle.h"
#include "Afterburner.h"
#include "Shaft.h"
#include "Solver.h"
#include "ISA.h"

// Map headers
#include "CompressorMap.h"
#include "TurbineMap.h"

// =========================================================================
// ScaleFactors — one set per component per operating point
// =========================================================================

struct ScaleFactors {
    double s_PR  = 1.0;
    double s_Ef  = 1.0;
    double s_Wc  = 1.0;
    double s_Nc  = 1.0;
};

// =========================================================================
// OperatingPoint — one row of measured (or synthetic) data
// =========================================================================

struct OperatingPoint {
    std::string label;      // e.g. "70% N_hp"

    // Flight conditions
    double altitude_ft = 35000.0;
    double MN          = 0.85;

    // Shaft speeds — independent variables for the solver
    double N_hp_init   = 0.0;   // initial guess [RPM]
    double N_lp_init   = 0.0;
    double W_init      = 60.0;

    // "Measured" performance — filled by running cycle or from real data
    // Fan
    double Wc_fan  = 0.0;
    double Nc_fan  = 0.0;
    double PR_fan  = 0.0;
    double eff_fan = 0.0;

    // HP Compressor
    double Wc_comp  = 0.0;
    double Nc_comp  = 0.0;
    double PR_comp  = 0.0;
    double eff_comp = 0.0;

    // HP Turbine
    double DhT_hp  = 0.0;
    double Nc_thp  = 0.0;
    double PR_thp  = 0.0;
    double eff_thp = 0.0;

    // LP Turbine
    double DhT_lp  = 0.0;
    double Nc_tlp  = 0.0;
    double PR_tlp  = 0.0;
    double eff_tlp = 0.0;
};

// =========================================================================
// MAP FILE PATHS
// =========================================================================

static const std::string MAP_DIR = "../maps/synthetic/";

// =========================================================================
// runCycle
//
// Runs the turbofan cycle at the given operating point initial conditions
// and fills the OperatingPoint struct with the converged station data.
// This is the "measurement" step — replace with real data loading
// when test cell data is available.
// =========================================================================

static bool runCycle(OperatingPoint& op)
{
    // --- Assemble engine ---
    const double altitude_m = ISA::feetToMeters(op.altitude_ft);

    Inlet      inlet(altitude_m, op.MN, 0.97);
    Fan        fan(3.5, 0.89);
    Splitter   splitter(0.8);
    Compressor compressor(8.0, 0.87);
    Combustor  combustor(CombustorMode::Tt4, 1700.0, 0.0, 0.99, 0.04);
    Turbine    turbine_hp(2.4186, 0.89, 0.005);
    Turbine    turbine_lp(1.9663, 0.89, 0.003);
    Afterburner afterburner(2100.0);
    Nozzle     nozzle(altitude_m, 0.98);
    FanNozzle  fanNozzle(altitude_m, 0.98);

    // Load maps
    inlet.loadMap     (MAP_DIR + "inlet.map");
    fan.loadMap       (MAP_DIR + "fan.map");
    compressor.loadMap(MAP_DIR + "hp_compressor.map");
    combustor.loadMap (MAP_DIR + "combustor.map");
    turbine_hp.loadMap(MAP_DIR + "hp_turbine.map");
    turbine_lp.loadMap(MAP_DIR + "lp_turbine.map");
    nozzle.loadMap    (MAP_DIR + "nozzle.map");
    fanNozzle.loadMap (MAP_DIR + "fan_nozzle.map");

    // Shafts
    Shaft hpShaft("HP Shaft", 15000.0);
    Shaft lpShaft("LP Shaft",  8000.0);
    hpShaft.addElement(&compressor);
    hpShaft.addElement(&turbine_hp);
    lpShaft.addElement(&turbine_lp);

    compressor.connectShaft(&hpShaft);
    turbine_hp.connectShaft(&hpShaft);
    fan.connectShaft       (&lpShaft);
    turbine_lp.connectShaft(&lpShaft);

    const double W_target = op.W_init;

    // Cycle evaluator lambda
    auto cycleEval = [&](const std::vector<double>& x) -> std::vector<double>
    {
        hpShaft.setSpeed(x[0]);
        lpShaft.setSpeed(x[1]);
        inlet.flowIn.W = x[2];

        inlet.compute();
        fan.flowIn = inlet.flowOut;        fan.compute();
        splitter.flowIn = fan.flowOut;     splitter.compute();
        compressor.flowIn = splitter.flowOut; compressor.compute();
        combustor.flowIn = compressor.flowOut; combustor.compute();
        turbine_hp.flowIn = combustor.flowOut; turbine_hp.compute();
        turbine_lp.flowIn = turbine_hp.flowOut; turbine_lp.compute();
        afterburner.flowIn = turbine_lp.flowOut; afterburner.compute();
        nozzle.flowIn = afterburner.flowOut; nozzle.compute();
        fanNozzle.flowIn = splitter.bypassOut; fanNozzle.compute();

        hpShaft.computeBalance();
        lpShaft.computeBalance();

        const double FAR_lp = combustor.flowOut.FAR;
        const double F_lp   = turbine_lp.dHt * (1.0 + FAR_lp)
                            * splitter.flowOut.W
                            - fan.dHt * inlet.flowIn.W;
        const double F_W    = inlet.flowIn.W - W_target;

        return { hpShaft.getBalanceError(), F_lp, F_W };
    };

    Solver solver(cycleEval, {1.0e4, 1.0e4, 1.0});
    const std::vector<double> x0 = {op.N_hp_init, op.N_lp_init, op.W_init};
    const SolverResult result = solver.solve(x0);

    if (!result.converged) return false;

    // Re-run at converged conditions to read station data
    hpShaft.setSpeed(result.x[0]);
    lpShaft.setSpeed(result.x[1]);
    inlet.flowIn.W = result.x[2];

    inlet.compute();
    fan.flowIn = inlet.flowOut;           fan.compute();
    splitter.flowIn = fan.flowOut;        splitter.compute();
    compressor.flowIn = splitter.flowOut; compressor.compute();
    combustor.flowIn = compressor.flowOut; combustor.compute();
    turbine_hp.flowIn = combustor.flowOut; turbine_hp.compute();
    turbine_lp.flowIn = turbine_hp.flowOut; turbine_lp.compute();

    // Record "measured" data from converged cycle
    // Fan
    op.Wc_fan  = fan.Wc;
    op.Nc_fan  = fan.Nc;
    op.PR_fan  = fan.flowOut.Pt / inlet.flowOut.Pt;
    op.eff_fan = fan.eff_is;

    // HP Compressor
    op.Wc_comp  = compressor.Wc;
    op.Nc_comp  = compressor.Nc;
    op.PR_comp  = compressor.flowOut.Pt / splitter.flowOut.Pt;
    op.eff_comp = compressor.eff_is;

    // HP Turbine
    const double Cp_thp = Thermo::getCp(combustor.flowOut.Tt, combustor.flowOut.FAR);
    op.DhT_hp  = Cp_thp * (combustor.flowOut.Tt - turbine_hp.flowOut.Tt)
               / combustor.flowOut.Tt;
    op.Nc_thp  = result.x[0] / std::sqrt(combustor.flowOut.Tt / 288.15);
    op.PR_thp  = turbine_hp.PR_t;
    op.eff_thp = turbine_hp.eff_is;

    // LP Turbine
    const double Cp_tlp = Thermo::getCp(turbine_hp.flowOut.Tt, turbine_hp.flowOut.FAR);
    op.DhT_lp  = Cp_tlp * (turbine_hp.flowOut.Tt - turbine_lp.flowOut.Tt)
               / turbine_hp.flowOut.Tt;
    op.Nc_tlp  = result.x[1] / std::sqrt(turbine_hp.flowOut.Tt / 288.15);
    op.PR_tlp  = turbine_lp.PR_t;
    op.eff_tlp = turbine_lp.eff_is;

    return true;
}

// =========================================================================
// computeScaleFactors
//
// Computes Kurzke-Riegler scale factors at one operating point by
// comparing measured performance against unscaled map lookup.
//
// The map is queried at the measured (Wc, Nc) with all scale factors = 1.0
// to get the "raw" map values. The scale factors are then the ratio of
// measured to map values.
// =========================================================================

static ScaleFactors computeScaleFactors(const std::string& map_filepath,
                                         double Wc_perf,
                                         double Nc_perf,
                                         double PR_perf,
                                         double eff_perf)
{
    ScaleFactors sf;

    CompressorMap cmap(map_filepath);
    if (!cmap.isLoaded()) return sf;

    // Compressor/Fan — query at (Wc_perf, Nc_perf)
    const CompressorMapResult res = cmap.lookup(Wc_perf, Nc_perf);

    if (res.PR  > 1.0 + 1.0e-6) sf.s_PR = (PR_perf - 1.0) / (res.PR  - 1.0);
    if (res.eff > 1.0e-6)        sf.s_Ef = eff_perf / res.eff;

    // s_Wc and s_Nc remain 1.0 — synthetic data from same map
    sf.s_Wc = 1.0;
    sf.s_Nc = 1.0;

    return sf;
}

static ScaleFactors computeTurbineScaleFactors(const std::string& map_filepath,
                                                double DhT_perf,
                                                double Nc_perf,
                                                double PR_perf,
                                                double eff_perf)
{
    ScaleFactors sf;

    TurbineMap tmap(map_filepath);
    if (!tmap.isLoaded()) return sf;

    const TurbineMapResult res = tmap.lookup(DhT_perf, Nc_perf);

    if (res.PR  > 1.0 + 1.0e-6) sf.s_PR = (PR_perf  - 1.0) / (res.PR  - 1.0);
    if (res.eff > 1.0e-6)        sf.s_Ef = eff_perf  / res.eff;
    sf.s_Wc = 1.0;
    sf.s_Nc = 1.0;

    return sf;
}

// =========================================================================
// averageScaleFactors
// =========================================================================

static ScaleFactors averageScaleFactors(const std::vector<ScaleFactors>& sfs)
{
    ScaleFactors avg;
    if (sfs.empty()) return avg;

    avg.s_PR = 0.0; avg.s_Ef = 0.0; avg.s_Wc = 0.0; avg.s_Nc = 0.0;
    for (const auto& sf : sfs)
    {
        avg.s_PR += sf.s_PR;
        avg.s_Ef += sf.s_Ef;
        avg.s_Wc += sf.s_Wc;
        avg.s_Nc += sf.s_Nc;
    }
    const double n = static_cast<double>(sfs.size());
    avg.s_PR /= n; avg.s_Ef /= n; avg.s_Wc /= n; avg.s_Nc /= n;
    return avg;
}

// =========================================================================
// updateMapScaleFactors
//
// Reads a map file, updates the SCALE_* fields in the header,
// and writes the file back. Preserves all other content unchanged.
// =========================================================================

static bool updateMapScaleFactors(const std::string& filepath,
                                   const ScaleFactors& sf)
{
    // Read entire file
    std::ifstream fin(filepath);
    if (!fin.is_open())
    {
        std::cerr << "[data_reduction] ERROR: cannot open '" << filepath << "'\n";
        return false;
    }

    std::vector<std::string> lines;
    std::string line;
    while (std::getline(fin, line))
        lines.push_back(line);
    fin.close();

    // Replace SCALE_* lines in place
    bool found_PR = false, found_EFF = false, found_WC = false, found_NC = false;

    for (auto& l : lines)
    {
        std::istringstream iss(l);
        std::string kw;
        iss >> kw;

        auto fmtScale = [](double v) -> std::string {
            std::ostringstream os;
            os << std::fixed << std::setprecision(6) << v;
            return os.str();
        };

        if (kw == "SCALE_PR")  { l = "SCALE_PR    " + fmtScale(sf.s_PR);  found_PR  = true; }
        if (kw == "SCALE_EFF") { l = "SCALE_EFF   " + fmtScale(sf.s_Ef);  found_EFF = true; }
        if (kw == "SCALE_WC")  { l = "SCALE_WC    " + fmtScale(sf.s_Wc);  found_WC  = true; }
        if (kw == "SCALE_NC")  { l = "SCALE_NC    " + fmtScale(sf.s_Nc);  found_NC  = true; }
    }

    if (!found_PR || !found_EFF || !found_WC || !found_NC)
    {
        std::cerr << "[data_reduction] WARNING: SCALE_* fields not found in '"
                  << filepath << "' — file may not have been generated by generate_maps\n";
    }

    // Write back
    std::ofstream fout(filepath);
    if (!fout.is_open())
    {
        std::cerr << "[data_reduction] ERROR: cannot write '" << filepath << "'\n";
        return false;
    }
    for (const auto& l : lines)
        fout << l << "\n";
    fout.close();

    return true;
}

// =========================================================================
// printScaleFactors
// =========================================================================

static void printScaleFactors(const std::string& name,
                               const ScaleFactors& sf)
{
    std::cout << std::fixed << std::setprecision(6);
    std::cout << "  " << name << ":\n";
    std::cout << "    s_PR  = " << sf.s_PR  << "\n";
    std::cout << "    s_Ef  = " << sf.s_Ef  << "\n";
    std::cout << "    s_Wc  = " << sf.s_Wc  << "\n";
    std::cout << "    s_Nc  = " << sf.s_Nc  << "\n";
}

// =========================================================================
// main
// =========================================================================

int main()
{
    std::cout << "========================================\n";
    std::cout << "  GasTurbineEngineModel — Phase 6\n";
    std::cout << "  Data Reduction Model\n";
    std::cout << "========================================\n\n";

    // =====================================================================
    // OPERATING POINTS
    // Define N power settings to run the cycle at.
    // These are synthetic — replace with real test cell data when available.
    //
    // Real data substitution guide:
    //   Replace N_hp_init/N_lp_init with measured shaft speeds.
    //   After runCycle(), overwrite op.Wc_fan, op.PR_fan, etc. with
    //   values computed from measured Pt and Tt at each station.
    // =====================================================================

    // Operating points — initial guesses close to known converged values
    // 70% and 80% use the 90% converged point as starting guess
    // since the synthetic maps have a narrow convergence basin at low speed
    std::vector<OperatingPoint> ops = {
        {"70% power",  35000.0, 0.85, 13500.0, 5800.0, 60.0},
        {"80% power",  35000.0, 0.85, 13800.0, 6000.0, 60.0},
        {"90% power",  35000.0, 0.85, 14000.0, 6200.0, 60.0},
        {"100% power", 35000.0, 0.85, 14557.0, 6452.0, 60.0},
    };

    std::cout << "Running cycle at " << ops.size()
              << " operating points...\n\n";

    // =====================================================================
    // RUN CYCLE AT EACH OPERATING POINT
    // =====================================================================

    int n_converged = 0;
    for (auto& op : ops)
    {
        std::cout << "  [" << op.label << "] ";
        std::cout.flush();

        if (runCycle(op))
        {
            ++n_converged;
            std::cout << "converged  "
                      << "PR_fan=" << std::fixed << std::setprecision(3)
                      << op.PR_fan
                      << "  PR_comp=" << op.PR_comp
                      << "  eff_fan=" << std::setprecision(4) << op.eff_fan
                      << "  eff_comp=" << op.eff_comp
                      << "\n";
        }
        else
        {
            std::cout << "DID NOT CONVERGE — skipping\n";
        }
    }

    std::cout << "\n" << n_converged << " / " << ops.size()
              << " operating points converged.\n\n";

    if (n_converged == 0)
    {
        std::cerr << "ERROR: no operating points converged — cannot compute scale factors\n";
        return 1;
    }

    // =====================================================================
    // COMPUTE SCALE FACTORS PER COMPONENT PER OPERATING POINT
    // =====================================================================

    std::cout << "Computing scale factors...\n\n";

    std::vector<ScaleFactors> sf_fan, sf_comp, sf_thp, sf_tlp;

    for (const auto& op : ops)
    {
        // Skip non-converged points (PR=0 signals failure)
        if (op.PR_fan < 1.0e-6) continue;

        sf_fan.push_back(computeScaleFactors(
            MAP_DIR + "fan.map",
            op.Wc_fan, op.Nc_fan, op.PR_fan, op.eff_fan));

        sf_comp.push_back(computeScaleFactors(
            MAP_DIR + "hp_compressor.map",
            op.Wc_comp, op.Nc_comp, op.PR_comp, op.eff_comp));

        sf_thp.push_back(computeTurbineScaleFactors(
            MAP_DIR + "hp_turbine.map",
            op.DhT_hp, op.Nc_thp, op.PR_thp, op.eff_thp));

        sf_tlp.push_back(computeTurbineScaleFactors(
            MAP_DIR + "lp_turbine.map",
            op.DhT_lp, op.Nc_tlp, op.PR_tlp, op.eff_tlp));
    }

    // =====================================================================
    // AVERAGE SCALE FACTORS ACROSS ALL OPERATING POINTS (MDP method)
    // =====================================================================

    const ScaleFactors avg_fan  = averageScaleFactors(sf_fan);
    const ScaleFactors avg_comp = averageScaleFactors(sf_comp);
    const ScaleFactors avg_thp  = averageScaleFactors(sf_thp);
    const ScaleFactors avg_tlp  = averageScaleFactors(sf_tlp);

    std::cout << "Averaged scale factors (Multi-Design-Point method):\n\n";
    printScaleFactors("Fan",         avg_fan);
    printScaleFactors("HP Compressor", avg_comp);
    printScaleFactors("HP Turbine",  avg_thp);
    printScaleFactors("LP Turbine",  avg_tlp);

    // =====================================================================
    // WRITE SCALE FACTORS TO MAP FILES
    // =====================================================================

    std::cout << "\nWriting scale factors to map files...\n";

    bool ok = true;
    ok &= updateMapScaleFactors(MAP_DIR + "fan.map",           avg_fan);
    ok &= updateMapScaleFactors(MAP_DIR + "hp_compressor.map", avg_comp);
    ok &= updateMapScaleFactors(MAP_DIR + "hp_turbine.map",    avg_thp);
    ok &= updateMapScaleFactors(MAP_DIR + "lp_turbine.map",    avg_tlp);

    if (ok)
    {
        std::cout << "  fan.map           — updated\n";
        std::cout << "  hp_compressor.map — updated\n";
        std::cout << "  hp_turbine.map    — updated\n";
        std::cout << "  lp_turbine.map    — updated\n";
    }

    // =====================================================================
    // SUMMARY
    // =====================================================================

    std::cout << "\n========================================\n";
    std::cout << "  Data Reduction Complete\n";
    std::cout << "  Operating points used : " << n_converged << "\n";
    std::cout << "  Method                : Multi-Design-Point average\n";
    std::cout << "  Reference             : Kurzke & Riegler ASME 2000-GT-0006\n";
    std::cout << "  Map files updated     : 4\n";
    std::cout << "\n";
    std::cout << "  Next steps:\n";
    std::cout << "    1. Run GasTurbineEngineModel to verify updated maps\n";
    std::cout << "    2. Replace synthetic data with real test cell data\n";
    std::cout << "    3. Re-run data_reduction with real data\n";
    std::cout << "========================================\n";

    return ok ? 0 : 1;
}