// =============================================================================
// generate_maps.cpp
// -----------------------------------------------------------------------------
// Standalone executable that generates synthetic performance map files
// for the GasTurbineEngineModel.
//
// OUTPUT: writes 7 map files to maps/synthetic/ (relative to project root)
//   fan.map
//   hp_compressor.map
//   hp_turbine.map
//   lp_turbine.map
//   nozzle.map
//   fan_nozzle.map
//   inlet.map
//
// DESIGN POINTS — from Phase 2 real gas solver results (main.cpp):
//   Fan          : PR=3.500, eff=0.89, Wc_d=60.00 kg/s
//   HP Compressor: PR=8.000, eff=0.87, Wc_d=33.33 kg/s
//   HP Turbine   : PR=2.363, eff=0.89, Tt_in=1700 K, Cp=1231 J/kg·K
//   LP Turbine   : PR=1.880, eff=0.89, Tt_in=1425 K, Cp=1203 J/kg·K
//   Core Nozzle  : NPR=6.53, Cfg=0.98
//   Fan Nozzle   : NPR=3.50, Cfg=0.98
//   Inlet        : MN=0.85,  eta_r=0.97
//
// SYNTHETIC MAP GENERATION METHOD:
//   Speed lines are generated at Nc = 70, 80, 90, 95, 100, 105 %
//
//   Compressor/Fan PR scaling:
//     PR(Nc) = 1 + (PR_d - 1) * (Nc/100)^n_PR
//     n_PR = 2.0 (fan), 2.2 (HP compressor)
//
//   Compressor/Fan efficiency scaling:
//     eff_peak(Nc) = eff_d * (1 - 0.15 * (1 - Nc/100)^2)
//     Parabolic hill along each speed line centred at mid-Wc
//
//   Turbine DhT range:
//     DhT_d computed from design point: Cp*(Tt_in - Tt_exit)/Tt_in
//     Speed lines span DhT = 0.5*DhT_d to 1.3*DhT_d
//     PR increases with DhT, efficiency peaks near design DhT
//
//   Nozzle Cfg:
//     Sigmoid rise from ~0.94 at NPR=1.0 to plateau at design Cfg
//
//   Inlet eta_r:
//     Parabolic drop from 1.0 at MN=0 to design eta_r at design MN
//
// SOURCE:
//   Mattingly, J.D., "Elements of Gas Turbine Propulsion",
//   McGraw-Hill, 1996. Appendix D — compressor map construction.
//   Walsh & Fletcher, "Gas Turbine Performance", 2nd ed.,
//   Blackwell, 2004. Chapter 8 — component characteristics.
// =============================================================================

#include <iostream>
#include <fstream>
#include <iomanip>
#include <cmath>
#include <string>
#include <vector>

// =========================================================================
// File header — written at the top of every map file
// =========================================================================

static const std::string FILE_HEADER =
    "# GasTurbineEngineModel — Synthetic Performance Map\n"
    "# Generated by tools/generate_maps.cpp\n"
    "# Source: synthetic — scaled from design point using similarity laws\n"
    "# Replace with real engine data when available.\n"
    "# See maps/README.md for format specification.\n"
    "#\n";

// =========================================================================
// writeHeader — writes the standard map file header block
// =========================================================================

static void writeHeader(std::ofstream&     f,
                        const std::string& type,
                        const std::string& name)
{
    f << FILE_HEADER;
    f << "TYPE        " << type << "\n";
    f << "NAME        " << name << "\n";
    f << "NC_UNITS    PERCENT\n";
    f << "SOURCE      SYNTHETIC\n";
    f << "\n";
}

// =========================================================================
// generateCompressorMap
//
// Generates a 2D compressor or fan map file.
//
// Speed lines at Nc = 70, 80, 90, 95, 100, 105 %
// Each speed line has 5 points from near-stall to near-choke.
//
// PR scaling:
//   PR(Nc) = 1 + (PR_d - 1) * (Nc/100)^n_PR
//
// Efficiency:
//   Peak eff at each speed = eff_d * (1 - 0.15 * (1 - Nc/100)^2)
//   Parabolic hill along the speed line centred at t=0.5
//
// Wc range per speed line:
//   Wc_design(Nc) = Wc_d * (Nc/100)
//   Wc_min = Wc_design * 0.60   (near stall)
//   Wc_max = Wc_design * 1.10   (near choke)
//
// VSV schedule (compressor only, not fan):
//   Vanes close progressively from design at Nc=100% to -15 deg at Nc=70%
// =========================================================================

static void generateCompressorMap(const std::string& filepath,
                                   const std::string& name,
                                   double             PR_d,
                                   double             eff_d,
                                   double             Wc_d,
                                   bool               has_vsv,
                                   double             n_PR)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(3);

    // --- Header ---
    writeHeader(f, "COMPRESSOR", name);
    f << "DESIGN_PT   Wc=" << Wc_d
      << "  Nc=100.0  PR=" << PR_d
      << "  eff=" << eff_d << "\n\n";

    // --- VSV schedule (compressor only) ---
    if (has_vsv)
    {
        // VSV closes at part speed to prevent stall
        // angle=0 at design, negative = vanes closing
        const std::vector<std::pair<double,double>> vsv = {
            {70.0, -15.0},
            {80.0, -10.0},
            {90.0,  -5.0},
            {95.0,  -2.0},
            {100.0,  0.0},
            {105.0,  0.0},
        };

        f << "VSV_SCHEDULE\n";
        for (const auto& pt : vsv)
            f << "  Nc=" << pt.first
              << "  angle=" << std::showpos << pt.second
              << std::noshowpos << "\n";
        f << "END_VSV_SCHEDULE\n\n";
    }

    // --- Speed lines ---
    const std::vector<double> nc_pcts = {70.0, 80.0, 90.0, 95.0, 100.0, 105.0};
    constexpr int N_PTS = 5;

    for (const double Nc : nc_pcts)
    {
        const double nc_frac = Nc / 100.0;

        // PR at design speed equals PR_d exactly — scale other speeds below it
        const double PR_design_speed = 1.0 + (PR_d - 1.0) * std::pow(nc_frac, n_PR);
        const double PR_peak = PR_design_speed;

        // Peak efficiency at this speed
        const double eff_peak = eff_d * (1.0 - 0.15 * std::pow(1.0 - nc_frac, 2.0));

        // Corrected flow range for this speed line
        const double Wc_design_nc = Wc_d * nc_frac;
        const double Wc_min       = Wc_design_nc * 0.72;   // design point near midpoint
        const double Wc_max       = Wc_design_nc * 1.28;   // of speed line for peak eff

        f << "SPEED_LINE  Nc=" << Nc << "\n";

        for (int k = 0; k < N_PTS; ++k)
        {
            const double t  = static_cast<double>(k) / (N_PTS - 1);
            const double Wc = Wc_min + t * (Wc_max - Wc_min);

            // PR varies symmetrically around PR_peak at t=0.5
            // At t=0.5 (design Wc): PR = PR_peak exactly
            const double PR_stall = PR_peak * 1.12;   // high PR near stall
            const double PR_choke = PR_peak * 0.88;   // low PR near choke
            // At t=0.5: PR = (PR_stall + PR_choke)/2 = PR_peak exactly
            const double PR       = PR_stall + t * (PR_choke - PR_stall);

            // Efficiency — parabolic hill centred at t=0.5
            double eff = eff_peak * (1.0 - 1.5 * std::pow(t - 0.5, 2.0));
            eff = std::min(eff, 0.96);
            eff = std::max(eff, 0.60);

            f << "  Wc=" << Wc
              << "  PR=" << PR
              << "  eff=" << eff << "\n";
        }

        f << "END_SPEED_LINE\n\n";
    }

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateTurbineMap
//
// Generates a 2D turbine map file.
// Axes: DhT [-] vs Nc [%]
// DhT = Cp * (Tt_in - Tt_exit) / Tt_in   [-]  (dimensionless energy function)
//
// NOTE: DhT [-] is NOT the same as dHt [J/kg] used in Turbine.cpp.
//
// Design DhT computed from:
//   Tt_exit_d = Tt_in_d - eff_d * Tt_in_d * (1 - (1/PR_d)^((gamma-1)/gamma))
//   DhT_d     = Cp_d * (Tt_in_d - Tt_exit_d) / Tt_in_d
//
// Speed lines span DhT = 0.50*DhT_d to 1.30*DhT_d.
// Turbine PR is nearly independent of Nc — slight variation modelled.
// Efficiency peaks near design DhT.
// =========================================================================

static void generateTurbineMap(const std::string& filepath,
                                const std::string& name,
                                double             PR_d,
                                double             eff_d,
                                double             Tt_in_d,
                                double             Cp_d)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(4);

    // Compute design DhT from real gas conditions
    // gamma approximated at turbine inlet (~1.315 for hot combustion products)
    constexpr double gamma_t = 1.315;
    constexpr double exp_t   = (gamma_t - 1.0) / gamma_t;

    const double Tt_exit_d = Tt_in_d
                           - eff_d * Tt_in_d * (1.0 - std::pow(1.0/PR_d, exp_t));
    const double DhT_d     = Cp_d * (Tt_in_d - Tt_exit_d) / Tt_in_d;

    // --- Header ---
    writeHeader(f, "TURBINE", name);
    f << "# DhT = Cp*(Tt_in - Tt_exit)/Tt_in [-]\n";
    f << "# NOTE: DhT [-] is NOT the same as dHt [J/kg] in Turbine.cpp\n";
    f << "DESIGN_PT   DhT=" << DhT_d
      << "  Nc=100.0  PR=" << PR_d
      << "  eff=" << eff_d << "\n\n";

    // --- Speed lines ---
    const std::vector<double> nc_pcts = {70.0, 80.0, 90.0, 95.0, 100.0, 105.0};
    constexpr int N_PTS = 5;

    for (const double Nc : nc_pcts)
    {
        const double nc_frac = Nc / 100.0;

        // Turbine PR — nearly constant with Nc, slight variation
        const double PR_nc = PR_d * (0.92 + 0.08 * nc_frac);

        // DhT range for this speed line
        const double DhT_min = DhT_d * 0.50;
        const double DhT_max = DhT_d * 1.30;

        f << "SPEED_LINE  Nc=" << std::setprecision(1) << Nc
          << std::setprecision(4) << "\n";

        for (int k = 0; k < N_PTS; ++k)
        {
            const double t   = static_cast<double>(k) / (N_PTS - 1);
            const double DhT = DhT_min + t * (DhT_max - DhT_min);

            // PR increases with DhT loading
            const double PR = 1.0 + (PR_nc - 1.0)
                            * std::pow(DhT / DhT_d, 0.8);

            // Efficiency — peaks near design DhT
            double eff = eff_d * (1.0 - 0.8 * std::pow(DhT/DhT_d - 1.0, 2.0));
            eff = std::min(eff, 0.93);
            eff = std::max(eff, 0.70);

            f << "  DhT=" << DhT
              << "  PR=" << std::setprecision(3) << PR
              << std::setprecision(4)
              << "  eff=" << eff << "\n";
        }

        f << "END_SPEED_LINE\n\n";
    }

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateNozzleMap
//
// Generates a 1D nozzle map: Cfg vs NPR.
// Cfg rises from ~0.94 at NPR=1 to plateau at design Cfg.
// Uses exponential approach to design value.
// =========================================================================

static void generateNozzleMap(const std::string& filepath,
                               const std::string& name,
                               double             NPR_d,
                               double             Cfg_d)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(4);

    // --- Header ---
    writeHeader(f, "NOZZLE", name);
    f << "DESIGN_PT   NPR=" << std::setprecision(2) << NPR_d
      << "  Cfg=" << std::setprecision(4) << Cfg_d << "\n\n";

    // NPR points — span from 1.0 to well above design
    const std::vector<double> NPR_pts = {
        1.00, 1.50, 2.00, 2.50, 3.00, 4.00,
        5.00, 6.00, 7.00, 8.00, 10.00, 12.00
    };

    f << "MAP_1D\n";
    for (const double NPR : NPR_pts)
    {
        // Cfg rises from low value at NPR=1 to plateau at design Cfg
        // Sigmoid-like curve: fast rise then plateau
        const double x   = (NPR - 1.0) / (NPR_d - 1.0);
        double Cfg = Cfg_d * (1.0 - 0.06 * std::exp(-3.0 * x));
        Cfg = std::min(Cfg, Cfg_d + 0.002);
        Cfg = std::max(Cfg, 0.930);

        f << "  NPR=" << std::setprecision(2) << NPR
          << "  Cfg=" << std::setprecision(4) << Cfg << "\n";
    }
    f << "END_MAP_1D\n";

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateInletMap
//
// Generates a 1D inlet map: eta_r vs MN.
// eta_r = 1.0 at MN=0, drops parabolically to design eta_r at design MN.
// =========================================================================

static void generateInletMap(const std::string& filepath,
                              const std::string& name,
                              double             MN_d,
                              double             eta_r_d)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed;

    // --- Header ---
    writeHeader(f, "INLET", name);
    f << "DESIGN_PT   MN=" << std::setprecision(2) << MN_d
      << "  eta_r=" << std::setprecision(4) << eta_r_d << "\n\n";

    // MN points from 0 to just above design MN
    const std::vector<double> MN_pts = {
        0.00, 0.20, 0.30, 0.40, 0.50,
        0.60, 0.70, 0.75, 0.80, 0.85,
        0.90, 0.95, 1.00
    };

    f << "MAP_1D\n";
    for (const double MN : MN_pts)
    {
        // Parabolic drop from 1.0 at MN=0 to eta_r_d at MN=MN_d
        double eta_r = 1.0 - (1.0 - eta_r_d) * std::pow(MN / MN_d, 2.0);
        eta_r = std::min(eta_r, 1.0000);
        eta_r = std::max(eta_r, 0.9000);

        f << "  MN=" << std::setprecision(2) << MN
          << "  eta_r=" << std::setprecision(4) << eta_r << "\n";
    }
    f << "END_MAP_1D\n";

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// main
// =========================================================================

int main()
{
    // Output directory — relative to build directory at runtime
    // Executable runs from build/, maps/synthetic/ is at ../maps/synthetic/
    const std::string OUT_DIR = "../maps/synthetic/";

    std::cout << "========================================\n";
    std::cout << "  generate_maps — Synthetic Map Generator\n";
    std::cout << "========================================\n\n";
    std::cout << "Output directory: " << OUT_DIR << "\n\n";

    // -------------------------------------------------------------------------
    // Fan map
    // Design: PR=3.5, eff=0.89, Wc_d=60.0 kg/s
    // No VSV — fans do not use variable stator vanes
    // -------------------------------------------------------------------------
    generateCompressorMap(
        OUT_DIR + "fan.map",
        "Fan",
        3.5,    // PR_d
        0.89,   // eff_d
        60.0,   // Wc_d [kg/s]
        false,  // has_vsv — fans do not have VSV
        2.0     // n_PR exponent
    );

    // -------------------------------------------------------------------------
    // HP Compressor map
    // Design: PR=8.0, eff=0.87, Wc_d=33.33 kg/s
    // VSV schedule included — HP compressor uses VSV for stall protection
    // -------------------------------------------------------------------------
    generateCompressorMap(
        OUT_DIR + "hp_compressor.map",
        "HP_Compressor",
        8.0,    // PR_d
        0.87,   // eff_d
        33.33,  // Wc_d [kg/s]
        true,   // has_vsv
        2.2     // n_PR exponent — higher than fan, steeper PR-speed relationship
    );

    // -------------------------------------------------------------------------
    // HP Turbine map
    // Design: PR=2.363, eff=0.89, Tt_in=1700 K, Cp=1231 J/kg·K
    // -------------------------------------------------------------------------
    generateTurbineMap(
        OUT_DIR + "hp_turbine.map",
        "HP_Turbine",
        2.363,   // PR_d
        0.89,    // eff_d
        1700.0,  // Tt_in_d [K]
        1231.0   // Cp_d [J/kg·K] — real gas value at Tt4
    );

    // -------------------------------------------------------------------------
    // LP Turbine map
    // Design: PR=1.880, eff=0.89, Tt_in=1425 K, Cp=1203 J/kg·K
    // -------------------------------------------------------------------------
    generateTurbineMap(
        OUT_DIR + "lp_turbine.map",
        "LP_Turbine",
        1.880,   // PR_d
        0.89,    // eff_d
        1425.0,  // Tt_in_d [K]
        1203.0   // Cp_d [J/kg·K] — real gas value at HP turbine exit
    );

    // -------------------------------------------------------------------------
    // Core nozzle map
    // Design: NPR=6.53, Cfg=0.98
    // -------------------------------------------------------------------------
    generateNozzleMap(
        OUT_DIR + "nozzle.map",
        "Core_Nozzle",
        6.53,   // NPR_d
        0.98    // Cfg_d
    );

    // -------------------------------------------------------------------------
    // Fan nozzle map
    // Design: NPR=3.50, Cfg=0.98
    // Bypass nozzle — lower NPR than core nozzle at design
    // -------------------------------------------------------------------------
    generateNozzleMap(
        OUT_DIR + "fan_nozzle.map",
        "Fan_Nozzle",
        3.50,   // NPR_d
        0.98    // Cfg_d
    );

    // -------------------------------------------------------------------------
    // Inlet map
    // Design: MN=0.85, eta_r=0.97
    // -------------------------------------------------------------------------
    generateInletMap(
        OUT_DIR + "inlet.map",
        "Flight_Inlet",
        0.85,   // MN_d
        0.97    // eta_r_d
    );

    std::cout << "\n========================================\n";
    std::cout << "  All map files written successfully\n";
    std::cout << "  Verify before wiring into elements\n";
    std::cout << "========================================\n";

    return 0;
}