// =============================================================================
// generate_maps.cpp
// -----------------------------------------------------------------------------
// Standalone executable that generates synthetic performance map files
// for the GasTurbineEngineModel.
//
// OUTPUT: writes 9 map files to maps/synthetic/ (relative to project root)
//   fan.map
//   hp_compressor.map
//   hp_turbine.map
//   lp_turbine.map
//   nozzle.map
//   fan_nozzle.map
//   inlet.map
//   turbojet_compressor.map
//   turbojet_hp_turbine.map
//
// DESIGN POINTS — from Phase 2 real gas solver results (main.cpp):
//   Fan          : PR=3.500, eff=0.89, Wc_d=60.00 kg/s
//   HP Compressor: PR=8.000, eff=0.87, Wc_d=33.33 kg/s
//   HP Turbine   : PR=2.363, eff=0.89, Tt_in=1700 K, Cp=1231 J/kg·K
//   LP Turbine   : PR=1.880, eff=0.89, Tt_in=1425 K, Cp=1203 J/kg·K
//   Core Nozzle  : NPR=6.53, Cfg=0.98
//   Fan Nozzle   : NPR=3.50, Cfg=0.98
//   Inlet        : MN=0.85,  eta_r=0.97
//
// SHAFT DESIGN SPEEDS (Phase 4 — NC_UNITS RPM):
//   HP shaft  : N_design = 15,000 RPM
//   LP shaft  : N_design =  8,000 RPM
//   Design inlet conditions: Tt_in = 250.4 K, T_ref = 288.15 K
//   theta     = sqrt(250.4 / 288.15) = 0.9328
//   HP Nc_d   = 15000 / 0.9328 = 16,091 RPM corrected
//   LP Nc_d   =  8000 / 0.9328 =  8,582 RPM corrected
//
// MAP AXES (Phase 4):
//   NC_UNITS RPM — speed lines stored in corrected RPM
//   Compressor/Fan: (Wc [kg/s], Nc [RPM corrected])
//   Turbine:        (DhT [-],   Nc [RPM corrected])
//
// PHASE 5 ADDITIONS:
//   SCALE_PR, SCALE_EFF, SCALE_WC, SCALE_NC — all 1.0 (no scaling active)
//   SURGE_LINE block — synthetic surge boundary for compressor and fan maps
//   Surge line sits ~12% above the operating PR at each corrected flow.
//   Shape: high PR_surge at low Wc, dropping toward choke — matches
//   published compressor surge line topology in Mattingly Appendix D
//   and Walsh & Fletcher Chapter 8.
//
// SOURCE:
//   Mattingly, J.D., "Elements of Gas Turbine Propulsion",
//   McGraw-Hill, 1996. Appendix D — compressor map construction.
//   Walsh & Fletcher, "Gas Turbine Performance", 2nd ed.,
//   Blackwell, 2004. Chapter 8 — component characteristics.
//   Kurzke, J. and Riegler, C., ASME 2000-GT-0006. — map scaling method.
// =============================================================================

#include <iostream>
#include <fstream>
#include <iomanip>
#include <cmath>
#include <string>
#include <vector>

// =========================================================================
// DESIGN SHAFT SPEEDS AND CORRECTED SPEED REFERENCE
// =========================================================================

static constexpr double N_HP_DESIGN  = 15000.0;
static constexpr double N_LP_DESIGN  =  8000.0;
static constexpr double Tt_IN_DESIGN = 250.4;
static constexpr double T_REF        = 288.15;

static const double Nc_HP_DESIGN = N_HP_DESIGN / std::sqrt(Tt_IN_DESIGN / T_REF);
static const double Nc_LP_DESIGN = N_LP_DESIGN / std::sqrt(Tt_IN_DESIGN / T_REF);

// =========================================================================
// File header
// =========================================================================

static const std::string FILE_HEADER =
    "# GasTurbineEngineModel — Synthetic Performance Map\n"
    "# Generated by tools/generate_maps.cpp\n"
    "# Source: synthetic — scaled from design point using similarity laws\n"
    "# Replace with real engine data when available.\n"
    "# See maps/README.md for format specification.\n"
    "#\n";

// =========================================================================
// writeHeader
// =========================================================================

static void writeHeader(std::ofstream&     f,
                        const std::string& type,
                        const std::string& name,
                        const std::string& nc_units)
{
    f << FILE_HEADER;
    f << "TYPE        " << type     << "\n";
    f << "NAME        " << name     << "\n";
    f << "NC_UNITS    " << nc_units << "\n";
    f << "SOURCE      SYNTHETIC\n";
    f << "\n";
}

// =========================================================================
// writeScaleFactors
//
// Writes Phase 5 Kurzke-Riegler scale factor fields to the map header.
// All set to 1.0 — no active scaling for synthetic maps.
// When real engine data is available, these values are updated in the
// map file to shift the generic reference map to match measured performance.
//
// Reference: Kurzke, J. and Riegler, C., ASME 2000-GT-0006.
// =========================================================================

static void writeScaleFactors(std::ofstream& f)
{
    f << "# Phase 5 — Kurzke-Riegler map scale factors\n";
    f << "# All 1.0 = no scaling active (synthetic map at design point)\n";
    f << "# Update from measured engine data for data reduction (Phase 6)\n";
    f << "SCALE_PR    1.000\n";
    f << "SCALE_EFF   1.000\n";
    f << "SCALE_WC    1.000\n";
    f << "SCALE_NC    1.000\n";
    f << "\n";
}

// =========================================================================
// generateCompressorMap
//
// Generates a 2D compressor or fan map file with NC_UNITS RPM.
// Phase 5 additions:
//   - SCALE_PR/EFF/WC/NC fields (all 1.0)
//   - SURGE_LINE block with synthetic surge boundary
//
// Surge line construction:
//   At each speed line the near-stall point is (Wc_min, PR_stall).
//   The surge line is placed 12% above the PR at the near-stall point,
//   giving realistic surge margin at design and part speed.
//   Shape matches Mattingly Appendix D — high PR_surge at low Wc,
//   decreasing toward choke Wc.
//
// @param Nc_design  Design corrected speed [RPM corrected]
// @param has_vsv    true = write VSV_SCHEDULE (compressor)
//                   false = write IGV_SCHEDULE placeholder (fan, Phase 5.2)
// =========================================================================

static void generateCompressorMap(const std::string& filepath,
                                   const std::string& name,
                                   double             PR_d,
                                   double             eff_d,
                                   double             Wc_d,
                                   double             Nc_design,
                                   bool               has_vsv,
                                   bool               has_igv,
                                   double             n_PR)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(3);

    // --- Header ---
    writeHeader(f, "COMPRESSOR", name, "RPM");

    // --- Phase 5: scale factors ---
    writeScaleFactors(f);

    // --- Design point ---
    f << "DESIGN_PT   Wc=" << Wc_d
      << "  Nc=" << std::setprecision(1) << Nc_design
      << std::setprecision(3)
      << "  PR=" << PR_d
      << "  eff=" << eff_d << "\n\n";

    // --- VSV schedule (compressor) ---
    if (has_vsv)
    {
        const std::vector<std::pair<double,double>> vsv_pcts = {
            {70.0, -15.0},
            {80.0, -10.0},
            {90.0,  -5.0},
            {95.0,  -2.0},
            {100.0,  0.0},
            {105.0,  0.0},
        };

        f << "VSV_SCHEDULE\n";
        for (const auto& pt : vsv_pcts)
        {
            const double Nc_rpm = Nc_design * pt.first / 100.0;
            f << "  Nc=" << std::setprecision(1) << Nc_rpm
              << "  angle=" << std::showpos << pt.second
              << std::noshowpos << "\n";
        }
        f << "END_VSV_SCHEDULE\n\n";
    }

    // --- IGV schedule (fan only) ---
    // IGV closes at part speed to protect fan from stall.
    // Less aggressive than compressor VSV — fan blade angles are larger
    // and more tolerant of incidence variation.
    // Schedule: 0 deg at design, closing to -10 deg at 70% speed.
    // Reference: Walsh & Fletcher Ch.8 — fan IGV scheduling.
    if (has_igv)
    {
        const std::vector<std::pair<double,double>> igv_pcts = {
            { 70.0, -10.0},
            { 80.0,  -5.0},
            { 90.0,  -2.5},
            { 95.0,  -1.0},
            {100.0,   0.0},
            {105.0,   0.0},
        };

        f << "IGV_SCHEDULE\n";
        for (const auto& pt : igv_pcts)
        {
            const double Nc_rpm = Nc_design * pt.first / 100.0;
            f << "  Nc=" << std::setprecision(1) << Nc_rpm
              << "  angle=" << std::showpos << pt.second
              << std::noshowpos << "\n";
        }
        f << "END_IGV_SCHEDULE\n\n";
    }

    // --- Phase 5: Surge line ---
    // Surge boundary computed from stall-side PR at each speed line.
    // PR_surge = PR_stall * 1.12  (12% above near-stall operating PR)
    // Wc_surge = Wc_min at each speed line
    // Shape: monotonically decreasing PR_surge with increasing Wc —
    // consistent with measured compressor surge lines (Mattingly App D).
    //
    // We compute surge points at each speed % then sort by Wc ascending
    // so the surge line is a clean monotonic curve from low to high Wc.
    {
        const std::vector<double> nc_pcts_surge =
            {70.0, 80.0, 90.0, 95.0, 100.0, 105.0};

        // Collect (Wc_surge, PR_surge) pairs
        struct SurgePt { double Wc; double PR; };
        std::vector<SurgePt> surge_pts;

        for (const double pct : nc_pcts_surge)
        {
            const double nc_frac    = pct / 100.0;
            const double PR_peak    = 1.0 + (PR_d - 1.0) * std::pow(nc_frac, n_PR);
            const double PR_stall   = PR_peak * 1.12;   // near-stall PR on speed line
            const double PR_surge   = PR_stall * 1.12;  // surge line 12% above stall
            const double Wc_design_nc = Wc_d * nc_frac;
            const double Wc_surge   = Wc_design_nc * 0.72;  // near-stall Wc
            surge_pts.push_back({Wc_surge, PR_surge});
        }

        f << "# Surge line — synthetic, 12% above near-stall PR at each speed\n";
        f << "# Source: Mattingly App D topology, scaled to design point\n";
        f << "SURGE_LINE\n";
        f << std::setprecision(3);
        for (const auto& pt : surge_pts)
            f << "  Wc=" << pt.Wc << "  PR=" << pt.PR << "\n";
        f << "END_SURGE_LINE\n\n";
    }

    // --- Speed lines ---
    const std::vector<double> nc_pcts = {70.0, 80.0, 90.0, 95.0, 100.0, 105.0};
    constexpr int N_PTS = 5;

    for (const double pct : nc_pcts)
    {
        const double nc_frac = pct / 100.0;
        const double Nc_rpm  = Nc_design * nc_frac;

        const double PR_peak  = 1.0 + (PR_d - 1.0) * std::pow(nc_frac, n_PR);
        const double eff_peak = eff_d * (1.0 - 0.15 * std::pow(1.0 - nc_frac, 2.0));

        const double Wc_design_nc = Wc_d * nc_frac;
        const double Wc_min       = Wc_design_nc * 0.72;
        const double Wc_max       = Wc_design_nc * 1.28;

        f << "SPEED_LINE  Nc=" << std::setprecision(1) << Nc_rpm
          << std::setprecision(3) << "\n";

        for (int k = 0; k < N_PTS; ++k)
        {
            const double t  = static_cast<double>(k) / (N_PTS - 1);
            const double Wc = Wc_min + t * (Wc_max - Wc_min);

            const double PR_stall = PR_peak * 1.12;
            const double PR_choke = PR_peak * 0.88;
            const double PR       = PR_stall + t * (PR_choke - PR_stall);

            double eff = eff_peak * (1.0 - 1.5 * std::pow(t - 0.5, 2.0));
            eff = std::min(eff, 0.96);
            eff = std::max(eff, 0.60);

            f << "  Wc=" << Wc
              << "  PR=" << PR
              << "  eff=" << eff << "\n";
        }

        f << "END_SPEED_LINE\n\n";
    }

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateTurbineMap — Phase 5: adds SCALE_* fields
// =========================================================================

static void generateTurbineMap(const std::string& filepath,
                                const std::string& name,
                                double             PR_d,
                                double             eff_d,
                                double             Tt_in_d,
                                double             Cp_d,
                                double             Nc_design)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(4);

    constexpr double gamma_t = 1.315;
    constexpr double exp_t   = (gamma_t - 1.0) / gamma_t;

    const double Tt_exit_d = Tt_in_d
                           - eff_d * Tt_in_d * (1.0 - std::pow(1.0/PR_d, exp_t));
    const double DhT_d     = Cp_d * (Tt_in_d - Tt_exit_d) / Tt_in_d;

    // --- Header ---
    writeHeader(f, "TURBINE", name, "RPM");

    // --- Phase 5: scale factors ---
    writeScaleFactors(f);

    // --- Design point ---
    f << "# DhT = Cp*(Tt_in - Tt_exit)/Tt_in [-]\n";
    f << "# NOTE: DhT [-] is NOT the same as dHt [J/kg] in Turbine.cpp\n";
    f << "DESIGN_PT   DhT=" << DhT_d
      << "  Nc=" << std::setprecision(1) << Nc_design
      << std::setprecision(4)
      << "  PR=" << PR_d
      << "  eff=" << eff_d << "\n\n";

    // --- Speed lines ---
    const std::vector<double> nc_pcts = {70.0, 80.0, 90.0, 95.0, 100.0, 105.0};
    constexpr int N_PTS = 5;

    for (const double pct : nc_pcts)
    {
        const double nc_frac = pct / 100.0;
        const double Nc_rpm  = Nc_design * nc_frac;

        const double PR_nc   = PR_d * (0.92 + 0.08 * nc_frac);
        const double DhT_min = DhT_d * 0.60;
        const double DhT_max = DhT_d * 1.40;

        f << "SPEED_LINE  Nc=" << std::setprecision(1) << Nc_rpm
          << std::setprecision(4) << "\n";

        for (int k = 0; k < N_PTS; ++k)
        {
            const double t   = static_cast<double>(k) / (N_PTS - 1);
            const double DhT = DhT_min + t * (DhT_max - DhT_min);

            const double PR_high = PR_nc * 1.12;
            const double PR_low  = PR_nc * 0.88;
            const double PR      = PR_high + t * (PR_low - PR_high);

            double eff = eff_d * (1.0 - 0.8 * std::pow(DhT/DhT_d - 1.0, 2.0));
            eff = std::min(eff, 0.93);
            eff = std::max(eff, 0.70);

            f << "  DhT=" << DhT
              << "  PR=" << std::setprecision(3) << PR
              << std::setprecision(4)
              << "  eff=" << eff << "\n";
        }

        f << "END_SPEED_LINE\n\n";
    }

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateCombustorMap
//
// Generates a combustor performance map with two 1D tables:
//   EFF_B_TABLE: eff_b vs FAR — combustion efficiency
//   DPQP_TABLE:  dPqP vs Wc_in — pressure loss
//
// EFF_B shape (Walsh & Fletcher Ch.6, Lefebvre & Ballal Ch.4):
//   Peak eff_b near FAR=0.025 (well within stability range for gas turbines)
//   Drops slightly at very low FAR (lean blowout approach)
//   Drops slightly at high FAR (rich, incomplete combustion)
//   Range: 0.970 – 0.9995
//
// DPQP shape:
//   Increases linearly with corrected inlet flow (dynamic pressure effect)
//   Range: 0.030 – 0.055 over typical Wc range
// =========================================================================

static void generateCombustorMap(const std::string& filepath,
                                  const std::string& name,
                                  double             FAR_design,
                                  double             eff_b_design,
                                  double             dPqP_design,
                                  double             Wc_design)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << FILE_HEADER;
    f << "TYPE        COMBUSTOR\n";
    f << "NAME        " << name << "\n";
    f << "SOURCE      SYNTHETIC\n";
    f << "# Reference: Walsh & Fletcher Ch.6, Lefebvre & Ballal Ch.4\n";
    f << "\n";

    f << std::fixed << std::setprecision(4);

    // --- EFF_B_TABLE: eff_b vs FAR ---
    // Shape: peak at FAR_design, drops at lean and rich extremes
    // Physical basis: poor atomisation at very low FAR, incomplete
    // combustion at very high FAR
    f << "# eff_b vs FAR — combustion efficiency\n";
    f << "# Peak at design FAR, drops at lean and rich extremes\n";
    f << "EFF_B_TABLE\n";

    const std::vector<std::pair<double,double>> eff_b_pts = {
        {0.005,  0.970},   // very lean — approaching stability limit
        {0.010,  0.985},   // lean
        {0.015,  0.992},   // part power
        {0.020,  0.997},   // approach design
        {FAR_design, eff_b_design},   // design point
        {0.035,  0.998},   // slightly rich
        {0.045,  0.995},   // rich
        {0.060,  0.985},   // very rich
        {0.080,  0.970},   // approaching rich blowout
    };

    for (const auto& pt : eff_b_pts)
        f << "  FAR=" << pt.first << "  eff_b=" << pt.second << "\n";

    f << "END_EFF_B_TABLE\n\n";

    // --- DPQP_TABLE: dPqP vs Wc_in ---
    // Shape: increases with corrected inlet flow (dynamic pressure scaling)
    // Anchored at design dPqP at design Wc
    f << "# dPqP vs Wc_in [kg/s corrected] — fractional pressure loss\n";
    f << "# Increases with corrected inlet flow (dynamic pressure effect)\n";
    f << "DPQP_TABLE\n";

    // Generate 5 points spanning 60% to 120% of design Wc
    for (int k = 0; k < 5; ++k)
    {
        const double frac  = 0.60 + k * 0.15;   // 0.60, 0.75, 0.90, 1.05, 1.20
        const double Wc    = Wc_design * frac;
        // dPqP scales with dynamic pressure ∝ Wc² — linear approx over small range
        const double dPqP  = dPqP_design * (0.80 + 0.20 * frac / 1.0);
        f << "  Wc=" << std::setprecision(2) << Wc
          << "  dPqP=" << std::setprecision(4) << dPqP << "\n";
    }

    f << "END_DPQP_TABLE\n";

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateNozzleMap — unchanged
// =========================================================================

static void generateNozzleMap(const std::string& filepath,
                               const std::string& name,
                               double             NPR_d,
                               double             Cfg_d)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed << std::setprecision(4);

    writeHeader(f, "NOZZLE", name, "PERCENT");
    f << "DESIGN_PT   NPR=" << std::setprecision(2) << NPR_d
      << "  Cfg=" << std::setprecision(4) << Cfg_d << "\n\n";

    const std::vector<double> NPR_pts = {
        1.00, 1.50, 2.00, 2.50, 3.00, 4.00,
        5.00, 6.00, 7.00, 8.00, 10.00, 12.00
    };

    f << "MAP_1D\n";
    for (const double NPR : NPR_pts)
    {
        const double x   = (NPR - 1.0) / (NPR_d - 1.0);
        double Cfg = Cfg_d * (1.0 - 0.06 * std::exp(-3.0 * x));
        Cfg = std::min(Cfg, Cfg_d + 0.002);
        Cfg = std::max(Cfg, 0.930);

        f << "  NPR=" << std::setprecision(2) << NPR
          << "  Cfg=" << std::setprecision(4) << Cfg << "\n";
    }
    f << "END_MAP_1D\n";

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// generateInletMap — unchanged
// =========================================================================

static void generateInletMap(const std::string& filepath,
                              const std::string& name,
                              double             MN_d,
                              double             eta_r_d)
{
    std::ofstream f(filepath);
    if (!f.is_open())
    {
        std::cerr << "[generate_maps] ERROR: cannot open '" << filepath << "'\n";
        return;
    }

    f << std::fixed;

    writeHeader(f, "INLET", name, "PERCENT");
    f << "DESIGN_PT   MN=" << std::setprecision(2) << MN_d
      << "  eta_r=" << std::setprecision(4) << eta_r_d << "\n\n";

    const std::vector<double> MN_pts = {
        0.00, 0.20, 0.30, 0.40, 0.50,
        0.60, 0.70, 0.75, 0.80, 0.85,
        0.90, 0.95, 1.00
    };

    f << "MAP_1D\n";
    for (const double MN : MN_pts)
    {
        double eta_r = 1.0 - (1.0 - eta_r_d) * std::pow(MN / MN_d, 2.0);
        eta_r = std::min(eta_r, 1.0000);
        eta_r = std::max(eta_r, 0.9000);

        f << "  MN=" << std::setprecision(2) << MN
          << "  eta_r=" << std::setprecision(4) << eta_r << "\n";
    }
    f << "END_MAP_1D\n";

    f.close();
    std::cout << "  Written: " << filepath << "\n";
}

// =========================================================================
// main
// =========================================================================

int main()
{
    const std::string OUT_DIR = "../maps/synthetic/";

    std::cout << "========================================\n";
    std::cout << "  generate_maps — Synthetic Map Generator\n";
    std::cout << "========================================\n\n";
    std::cout << "Output directory: " << OUT_DIR << "\n";
    std::cout << std::fixed << std::setprecision(1);
    std::cout << "HP design corrected speed: " << Nc_HP_DESIGN << " RPM\n";
    std::cout << "LP design corrected speed: " << Nc_LP_DESIGN << " RPM\n\n";

    // Fan — LP shaft, IGV schedule included (Phase 5.1)
    generateCompressorMap(
        OUT_DIR + "fan.map", "Fan",
        3.5, 0.89, 60.0, Nc_LP_DESIGN,
        false,   // has_vsv — fans use IGV not VSV
        true,    // has_igv — Phase 5.1
        2.0
    );

    // HP Compressor — HP shaft
    generateCompressorMap(
        OUT_DIR + "hp_compressor.map", "HP_Compressor",
        8.0, 0.87, 33.33, Nc_HP_DESIGN, true, false, 2.2
    );

    // HP Turbine — HP shaft
    generateTurbineMap(
        OUT_DIR + "hp_turbine.map", "HP_Turbine",
        2.363, 0.89, 1700.0, 1231.0, Nc_HP_DESIGN
    );

    // LP Turbine — LP shaft
    generateTurbineMap(
        OUT_DIR + "lp_turbine.map", "LP_Turbine",
        1.880, 0.89, 1425.0, 1203.0, Nc_LP_DESIGN
    );

    // Turbojet HP Compressor
    // Wc_d = 20 * sqrt(250.4/288.15) / (37090/101325) = 50.96 kg/s corrected
    generateCompressorMap(
        OUT_DIR + "turbojet_compressor.map", "TJ_HP_Compressor",
        10.0, 0.87, 50.96, Nc_HP_DESIGN, true, false, 2.2
    );

    // Turbojet HP Turbine
    generateTurbineMap(
        OUT_DIR + "turbojet_hp_turbine.map", "TJ_HP_Turbine",
        2.246, 0.89, 1400.0, 1199.66, Nc_HP_DESIGN
    );

    // Turbofan combustor map
    // Design: FAR=0.027, eff_b=0.999, dPqP=0.04, Wc_in=33.33 kg/s
    generateCombustorMap(
        OUT_DIR + "combustor.map", "TF_Combustor",
        0.027, 0.999, 0.04, 33.33
    );

    // Turbojet combustor map
    // Design: FAR=0.022, eff_b=0.999, dPqP=0.04, Wc_in=20.0 kg/s
    generateCombustorMap(
        OUT_DIR + "turbojet_combustor.map", "TJ_Combustor",
        0.022, 0.999, 0.04, 20.0
    );

    // Core nozzle — restored (was missing from previous main())
    generateNozzleMap(OUT_DIR + "nozzle.map",     "Core_Nozzle",  6.53, 0.98);
    generateNozzleMap(OUT_DIR + "fan_nozzle.map", "Fan_Nozzle",   3.50, 0.98);
    generateInletMap (OUT_DIR + "inlet.map",      "Flight_Inlet", 0.85, 0.97);

    std::cout << "\n========================================\n";
    std::cout << "  All map files written successfully\n";
    std::cout << "  Verify before wiring into elements\n";
    std::cout << "========================================\n";

    return 0;
}